import { LegalDocument } from '../components/LegalDocument'
import { Seo } from '../components/Seo'
import { siteConfig } from '../config/site'

export function PrivacyPage() {
  return <><Seo title="Privacy Policy" description="Read how Memoir handles recordings, memoir content, AI processing, iCloud, photos, purchases, and deletion." path="/privacy" />
    <LegalDocument title="Privacy Policy for Memoir" intro="This policy explains what information Memoir handles, why it is needed, and the choices available to you.">
      <section><h2>1. Introduction</h2><p>Memoir is operated by {siteConfig.companyName}. Memoir helps you record memories, shape them into written Echoes, organize a living memoir, attach photographs, and export a printable book. This policy describes information handled when you use the Memoir app.</p></section>
      <section><h2>2. Information you provide</h2><p>Depending on the features you choose, Memoir may handle dictated memoir text, saved Echoes, moods, Sparks, chapter titles and descriptions, tags, people and places mentioned in your stories, Narrator Mirror observations, and photographs you select. This information may be deeply personal. You decide what to record and save.</p></section>
      <section><h2>3. Audio and speech recognition</h2><p>Memoir requests microphone access when you choose to dictate a memory. Audio is used to produce a transcription. Memoir does not permanently retain the audio recording after transcription.</p><p>Speech recognition may depend on services provided by Apple and the operating system. Those services are governed by Apple’s terms and privacy practices, and their processing or retention practices may differ from Memoir’s.</p></section>
      <section><h2>4. AI processing</h2><p>Only after you grant permission, Memoir may send memoir text and relevant context to an external AI provider. The current intended provider is OpenAI; this must be confirmed against the production configuration before publication.</p><p>Information sent may include your transcript, an Echo draft, relevant chapter information, a Spark, selected mood or tone, and limited Narrator Mirror context. It is processed to organize a memory, refine wording while preserving your voice, suggest structure, or create reflective observations.</p><p>You can withdraw permission for future AI processing in the app. Withdrawal stops new AI requests; it does not automatically delete Echoes or other results already saved in your memoir. The external provider’s own handling is governed by the applicable service agreement and privacy terms. Memoir does not make an unverified claim here about provider retention or model training.</p></section>
      <section><h2>5. Local storage, iCloud, and CloudKit</h2><p>Memoir is designed as a local-first app. Your memoir is stored on your device and may synchronize through the private iCloud account signed into that device using Apple’s iCloud and CloudKit infrastructure. No separate Memoir account is required.</p><p>iCloud availability and data handling are also subject to your Apple ID settings and Apple’s terms. Turning off iCloud may pause synchronization without removing copies already present on your devices or in iCloud.</p></section>
      <section><h2>6. Photos</h2><p>Memoir accesses only photographs you choose to attach. Selected images are used to illustrate the relevant Echo and are stored with memoir data locally and, when enabled, through iCloud synchronization. Your wider photo library is not copied into Memoir.</p></section>
      <section><h2>7. PDF export and sharing</h2><p>You can create a PDF of your memoir and choose where to save or share it. Once a PDF or other export leaves Memoir, it is controlled by you and by the destination you select. Other apps, cloud services, recipients, or share-sheet destinations have their own privacy practices.</p></section>
      <section><h2>8. Purchases and Ink</h2><p>Ink is Memoir’s usage-credit mechanism. Purchases are processed by Apple through StoreKit. Memoir does not receive your complete payment-card details. Apple may retain purchase and transaction records under its own policies, including records needed to restore purchases.</p></section>
      <section><h2>9. Data retention</h2><p>Memoir content remains available while you keep it in the app, subject to your device storage and iCloud configuration. Exported copies remain wherever you place them. External services may apply their own retention rules; no specific processor retention period is stated until it has been verified.</p></section>
      <section><h2>10. Data deletion</h2><p>The app provides a <strong>Delete My Memoir</strong> action intended to remove memoir content controlled by the app, including saved Echoes, chapters, Sparks, Narrator Mirror information, and app-managed photo attachments. The exact production scope of local and CloudKit deletion must be verified before this policy is treated as final.</p><p>Deletion does not remove PDFs or copies you previously exported or shared, information held by recipients, or Apple purchase history. Withdrawal of AI permission does not delete existing Echoes.</p></section>
      <section><h2>11. Security</h2><p>Memoir uses reasonable technical and organizational safeguards appropriate to the nature of the app. No device, transmission, or storage system can be guaranteed completely secure. Protect your device, Apple ID, passcode, and exported files.</p></section>
      <section><h2>12. Children</h2><p>Memoir is not directed to children below the minimum age permitted for independent use in their location. Memoir does not provide a parental account or parental-consent workflow in this version. The intended App Store age rating and applicable minimum age require confirmation before publication.</p></section>
      <section><h2>13. International processing</h2><p>When external speech or AI services are used, information may be processed in countries other than the one where you live. Applicable safeguards depend on the production providers, account configuration, and governing agreements and should be confirmed before release.</p></section>
      <section><h2>14. Changes to this policy</h2><p>We may update this policy as Memoir evolves or legal requirements change. The current version and effective date will be posted on this page. Material changes may also be communicated in the app when appropriate.</p></section>
      <section><h2>15. Contact</h2><p>For privacy questions or requests, email <a href={`mailto:${siteConfig.privacyEmail}`}>{siteConfig.privacyEmail}</a>.</p></section>
    </LegalDocument></>
}
