import { LegalDocument } from '../components/LegalDocument'
import { Seo } from '../components/Seo'
import { siteConfig } from '../config/site'

export function TermsPage() {
  return <><Seo title="Terms of Service" description="Terms governing your use of Memoir, including content ownership, AI-assisted features, Ink, exports, and availability." path="/terms" />
    <LegalDocument title="Terms of Service for Memoir" intro="These terms are intended to set clear, understandable expectations for using Memoir.">
      <section><h2>1. Acceptance of terms</h2><p>By downloading, accessing, or using Memoir, you agree to these Terms of Service. If you do not agree, do not use the app. These terms are between you and {siteConfig.companyName}, the operator of Memoir.</p></section>
      <section><h2>2. Purpose of Memoir</h2><p>Memoir is a personal storytelling tool that helps you record, organize, refine, read, and export memories. It is not a professional medical, psychological, legal, historical-verification, or archival service.</p></section>
      <section><h2>3. Your content and ownership</h2><p>You retain ownership of the memoir text, recordings, photographs, and other original content you provide. You grant {siteConfig.companyName} a limited, non-exclusive license to process that content only as reasonably necessary to operate features you request, such as transcription, refinement, synchronization, and export. This license ends when the content is deleted from systems controlled by Memoir, subject to necessary technical processing and obligations of external providers.</p></section>
      <section><h2>4. AI-assisted content</h2><p>Some features use AI to organize, rewrite, summarize, or reflect on text. AI output may be inaccurate, incomplete, or different from what you intended. You are responsible for reviewing every generated or refined Echo before relying on, publishing, or sharing it. Memoir does not claim that AI output is a factual historical record or a substitute for your judgment.</p></section>
      <section><h2>5. Acceptable use</h2><p>You must not use Memoir to violate law, infringe another person’s rights, distribute malicious material, attempt unauthorized access, interfere with the service, or process content you do not have the right to use. You are responsible for obtaining permission before recording or publishing information about other people where required.</p></section>
      <section><h2>6. Memoir intellectual property</h2><p>Memoir, its branding, interface, software, and original materials are owned by {siteConfig.companyName} or its licensors. These terms do not transfer those rights to you. You may use the app only for its intended personal purposes and in accordance with applicable store rules.</p></section>
      <section><h2>7. Purchases and Ink</h2><p>Ink is the app’s usage-credit mechanism for eligible processing features. Purchases are made through Apple’s StoreKit and are subject to Apple’s payment terms. Prices and available packages may change. Refund eligibility and processing are governed by Apple where applicable. Your Ink balance is not money, is not transferable, and has no cash value unless law requires otherwise.</p></section>
      <section><h2>8. Service availability and changes</h2><p>We aim to keep Memoir available and reliable, but features may be interrupted by device conditions, iCloud, Apple services, network access, external AI providers, maintenance, or events outside our control. We may update, change, suspend, or discontinue features where reasonably necessary.</p></section>
      <section><h2>9. Backups and data loss</h2><p>Memoir is local-first and may use your iCloud account, but you remain responsible for your device, iCloud configuration, and exported backups. You should periodically export important memoirs. To the extent permitted by law, {siteConfig.companyName} is not responsible for loss caused by device failure, account loss, disabled synchronization, third-party outages, user deletion, or destinations outside Memoir’s control.</p></section>
      <section><h2>10. Disclaimers</h2><p>Memoir is provided on an “as available” basis. To the maximum extent allowed by law, we disclaim implied warranties that cannot reasonably apply to a personal storytelling tool. Nothing in these terms excludes consumer guarantees or other rights that cannot lawfully be excluded.</p></section>
      <section><h2>11. Limitation of liability</h2><p>To the extent permitted by applicable law, {siteConfig.companyName} will not be liable for indirect, incidental, special, consequential, or exemplary losses arising from use of Memoir. Any monetary cap, governing-law clause, venue, and jurisdiction-specific consumer wording must be confirmed before these terms are considered legally final.</p></section>
      <section><h2>12. Termination or discontinuation</h2><p>You may stop using Memoir at any time. We may restrict use where reasonably necessary to address serious misuse, legal obligations, security risks, or harm to the service. If Memoir is discontinued, reasonable notice will be provided where practical, but you should maintain exports of content you wish to preserve.</p></section>
      <section><h2>13. Changes to these terms</h2><p>We may update these terms to reflect product, legal, or operational changes. The current version and effective date will be posted here. Continued use after an update takes effect means you accept the revised terms where permitted by law.</p></section>
      <section><h2>14. Contact</h2><p>Questions about these terms can be sent to <a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a>.</p></section>
    </LegalDocument></>
}
